"use strict";stopSpinner();Modernizr.on('webp',function(result){if(result){document.body.classList.add("webp");}else{document.body.classList.add("no-webp");}});$(document).ready(function(){$('.social-share').each(function(){var li=$(this).children("li");li.children("a").attr("rel","nofollow noopener");});$(".fBox").fancybox();$(".video-audio-review-content-video").slick({dots:true,infinite:true,slidesToShow:3,slidesToScroll:3,centerMode:true,responsive:[{breakpoint:991,settings:{slidesToShow:1,slidesToScroll:1,infinite:true,dots:false,centerMode:false}}]});$(document).on("click",".one-video-review a",function(e){e.preventDefault();var link=$(this);var url=link.attr("data-video-url");$(".video-review-modal iframe").attr("src",url);});Inputmask({"regex":"[a-zA-Zа-яА-Я- ]*","onBeforePaste":function(pastedValue,opts){return false;}}).mask($("input.inputmask-name"));Inputmask({"onBeforePaste":function(pastedValue,opts){return false;}}).mask($("#reviews-form-input-text"));if(!isMobileDevice()){$('body').addClass('desktop');}
$(window).scroll(function(){$('.news-hide').each(function(i,el){if($(window).scrollTop()+$(window).height()>=$(el).offset().top){$(el).show();}});});setTimeout(function(){$('#all-loader').hide();$('#all-wrap').show();},2000);$(document).mouseup(function(e){var div=$(".modal__city-body--search-chosen");if(!div.is(e.target)&&div.has(e.target).length===0){div.hide();}});$('.show-all-news.visibility-trigger').on("click",function(){$('.newslist-item').removeClass('hidden');$('.show-all-news').addClass('hidden');});$("#inputCity").on("input",function(){viewCity(this.value);});$('.scroll-link').on("click",function(){$($(this).attr('href')).scrollView();});$('.open-modal-request').click(function(event){$('#modalRequest').modal('show');event.preventDefault();});$('#reviews-submit, #contacts-submit').click(function(event){event.preventDefault();let formName=event.target.id.replace(/-submit/i,'');let isPhoneValid=validatePhone($('#'+formName+'-form-input-tel').val(),formName);let isTextAndNameValid=validateReviewNameAndText(formName);if(isPhoneValid&&isTextAndNameValid){send(document.querySelector("#"+formName+"-form"),event);viewResponse(formName,event);}});$('input[type=file]').change(function(){files=this.files;});$('#request-form-input').focus(function(){$('#modalRequest').scrollTop(150);});[].forEach.call(document.querySelectorAll('img[data-src]'),function(img){img.setAttribute('src',img.getAttribute('data-src'));img.onload=function(){img.removeAttribute('data-src');};});initAfterPjax();$(window).resize(fixWorkersCountMargin).resize(fixCalcWidgets).resize(initShowMoreButtons).ready(function(){fixWorkersCountMargin();fixCalcWidgets();initShowMoreButtons();});$('.si.si-odnoklassniki, .si.si-facebook').each(function(){let parent=$(this).parent();parent.addClass('icon-bg-gray');if($(this).hasClass('si-odnoklassniki')){parent.addClass('alt');}});if(document.getElementById('scrollMenuTrigger').getBoundingClientRect().top<0){$('#scrollMenuElement').css({'display':'block','transform-style':'preserve-3d','transform':'translateX(0px) translateY(0px) translateZ(0px)','transition':'transform 400ms ease 0s'});}
$(document).on('ready pjax:end',function(event){initAfterPjax();});$(document).on('click','.close, .close_bg',function(e){e.preventDefault();$('.modal-city').hide();});$(document).on('click','.video-audio-review-tabs li a',function(e){e.preventDefault();var link=$(this);var tab=link.attr("data-tab");$(".video-audio-review-tabs li").removeClass("active");link.parent("li").addClass("active");$(".video-audio-review-content > div").hide();$("."+tab).show();$(".video-audio-review-content-audio").slick({dots:true,infinite:true,slidesToShow:3,slidesToScroll:3,centerMode:true,responsive:[{breakpoint:991,settings:{slidesToShow:1,slidesToScroll:1,infinite:true,dots:false,centerMode:false}}]});});});function stopSpinner(){let calcPreloader=document.getElementById('calcPreloader');if(calcPreloader){window.addEventListener('load',function(){calcPreloader.className+=" hidden";});}}
function initAfterPjax(){$('.fakeLink').click(function(){return false;});$('input.iCheck_calc').each(function(){let self=$(this);let label=self.next();let label_text=label.html();label.remove();self.iCheck({checkboxClass:'icheckbox_line-yellow',radioClass:'iradio_line-yellow',insert:'<div class="icheck_line-icon"></div>'+label_text});});if($('[data-flavor="testimonial"]').length>0){$('[data-flavor="testimonial"]').flavor();}
$('input.iCheck_calc-alt').each(function(){let self=$(this);let label=self.next();let label_text='<span>'+label.html()+'</span>';self.iCheck({checkboxClass:'icheckbox_flat-yellow',radioClass:'iradio_flat-yellow',});});$('#request-submit, #request1-submit, #request2-submit, #calc-submit').click(function(event){event.preventDefault();let formName=event.target.id.replace(/-submit/i,'');if(validatePhone($('#'+formName+'-form-input').val(),formName)){send(document.querySelector('#'+formName+'-form'),event);viewResponse(formName,event);}});$('[data-ix="open-modal-city"]').on('click',function(){$('#inputCity').trigger('focus');});Inputmask({"mask":"+7 (\\999) 999-99-99","onBeforePaste":function(pastedValue,opts){return false;}}).mask($("input[type='tel']"));let wfCopy=wfEvents;wfCopy.pop();Webflow.require('ix').init(wfCopy);initShowMoreButtons();$('#submit-calc').click(function(){let workersCount=$('input[name="workers_count"]:checked').val();let workStartsDate=$('input[name="work_starts_date"]').val();let workStartsTime=$('select[name="work_starts_time"]').val();let carNeed=$('input[name="car_need"]:checked').val();let additionalOptions=[];$('.additional_need .icheckbox_flat-yellow.checked > input').each(function(i,el){additionalOptions.push($(el).val());});if(workersCount){$('#workers_count').val(workersCount);}
if(workStartsDate){$('#work_starts').val(workStartsDate);}
if(workStartsTime){$('#work_starts').val($('#work_starts').val()+' '+workStartsTime);}
if(carNeed){$('#car_need').val(carNeed);}
if(additionalOptions.length>0){$('#additional_options').val(additionalOptions.join(', '));}})
$('#submit-order').click(function(){let workerId=$('input[name="worker_id"]').val();let groupId=$('input[name="group_id"]').val();let priceId=$('input[name="price_id"]').val();let additionalOptions=[];if(workerId){$('#worker_id').val(workerId);}
if(groupId){$('#group_id').val(groupId);}
if(priceId){$('#price_id').val(priceId);}});}
function initShowMoreButtons(){let screenWidth=window.innerWidth;if(screenWidth>=768){$('.tags_service_cont').not('[data-readmore]').readmore({speed:85,collapsedHeight:70,blockCSS:'display: block; width: 100%; overflow: hidden;',moreLink:'<a class="showmore-button" href="#">Показать все</a>',lessLink:'<a class="showmore-button showed" href="#">Свернуть</a>'});$('.paragraph._1.service-page[data-readmore]').readmore('destroy');}else{$('.tags_service_cont[data-readmore]').readmore('destroy');$('.paragraph._1.service-page').not('[data-readmore]').readmore({speed:85,collapsedHeight:160,blockCSS:'display: block; width: 100%; overflow: hidden;',moreLink:'<a class="showmore-button" href="#">Показать весь текст</a>',lessLink:'<a class="showmore-button showed" href="#">Свернуть</a>'});}
if(screenWidth<480){$('.seo_text_footer').not('[data-readmore]').readmore({speed:85,collapsedHeight:120,blockCSS:'display: block; width: 100%; overflow: hidden;',moreLink:'<a class="showmore-button" href="#">Показать все</a>',lessLink:'<a class="showmore-button showed" href="#">Свернуть</a>'});}else{$('.seo_text_footer[data-readmore]').readmore('destroy');}}
function fixWorkersCountMargin(){let wrapWidth=$('.workers_count').outerWidth();let elemWidth=$('.workers_count > div:first-of-type').outerWidth();let elemsCount=$('.workers_count > div').length;let elemsInRow=Math.trunc(wrapWidth/elemWidth);let elemMargin=(wrapWidth-elemWidth*elemsInRow)/(elemsInRow-1);let lastRowLen=elemsCount%elemsInRow;$('.workers_count > div').css('margin-right','').each(function(i,el){if(i>(elemsCount-lastRowLen-1)&&i!=(elemsCount-1)&&window.innerWidth<=480){$(el).css('margin-right',elemMargin+'px');}});}
function fixCalcWidgets(){let select2Width=$('#calcWidgets .select2-selection--single').outerWidth();switch(true){case select2Width>168:$('#calcWidgets').removeClass().addClass('work_starts');break;case select2Width>153&&select2Width<=168:$('#calcWidgets').removeClass().addClass('work_starts fix168');break;case select2Width>142&&select2Width<=153:$('#calcWidgets').removeClass().addClass('work_starts fix153');break;case select2Width>132&&select2Width<=142:$('#calcWidgets').removeClass().addClass('work_starts fix142');break;case select2Width<=132:$('#calcWidgets').removeClass().addClass('work_starts fix132');break;}}
function isMobileDevice(){return(typeof window.orientation!=="undefined")||(navigator.userAgent.indexOf('IEMobile')!==-1);};function validatePhone(number,formName){let valid=/^[+][7][ ][(][0-9]{3}[)][ ][0-9]{3}[-][0-9]{2}[-][0-9]{2}$/.test(number);if(valid){$('#'+formName+'-error > div').html('');$('#'+formName+'-error').slideUp(250);$('#'+formName+'-form-input').removeClass('invalid');$('#'+formName+'-form-input-tel').removeClass('invalid');return true;}
$('#'+formName+'-form-input').addClass('invalid');$('#'+formName+'-form-input-tel').addClass('invalid');$('#'+formName+'-error > div').html('<div>Неверно введен номер телефона</div>');$('#'+formName+'-error').slideDown(250);return false;}
function validateReviewNameAndText(formName){let validName=($('#'+formName+'-form-input-name').val().length>=2);let validText=($('#'+formName+'-form-input-text').val().length>=10);if(validName&&validText){if($('#'+formName+'-error > div').html()==''){$('#'+formName+'-error').slideUp(250);$('#'+formName+'-error > div').html('');}
$('#'+formName+'-form-input-name').removeClass('invalid');$('#'+formName+'-form-input-text').removeClass('invalid');return true;}
if(!validName){$('#'+formName+'-form-input-name').addClass('invalid');$('#'+formName+'-error > div').html($('#'+formName+'-error > div').html()
+'<div>Минимальная длина имени 2 символа</div>');}else{$('#'+formName+'-form-input-name').removeClass('invalid');}
if(!validText){$('#'+formName+'-form-input-text').addClass('invalid');$('#'+formName+'-error > div').html($('#'+formName+'-error > div').html()
+'<div>Минимальная длина текста 10 символов</div>');}else{$('#'+formName+'-form-input-text').removeClass('invalid');}
$('#'+formName+'-error').slideDown(250);return false;}
function viewResponse(formName,event){$('#'+formName+'-response').slideDown(250);$('#'+formName+'-submit').attr('disabled',true);event.preventDefault();}
function viewCity(citiesLink,filter=null){let html='';$('.modal__city-body--search-chosen').width($('#inputCity').innerWidth());$(".modal__city-body--search-chosen").hide();if(filter){for(let cityName in citiesLink){let _cityName=cityName.toLowerCase();if(filter&&_cityName.indexOf(filter.toLowerCase())!=0){continue;}
html+='<li><a href="'+citiesLink[cityName]+'">'+cityName+'</a></li>'}
if(!html){html='<li>Ничего не найдено</li>';}
$("#cityList").html(html);$(".modal__city-body--search-chosen").show();}}
$.fn.scrollView=function(){return this.each(function(){$('html, body').animate({scrollTop:$(this).offset().top},1000);});};var files;function send(form,event){event.stopPropagation();event.preventDefault();var data=new FormData(form);$.each(files,function(key,value){data.append(key,value);});$.ajax({url:'/ajax/contact',type:'POST',data:data,cache:false,processData:false,contentType:false,success:function(respond,textStatus,jqXHR){if(typeof respond.error==='undefined'){if(data.has('Message[workerId]')){$(form).trigger("reset");$('#reviews-submit').removeAttr('disabled');$('.modal-review').hide();$.pjax.reload({container:'#listReview',timeout:false,async:false,cache:false});if($('#totalCountReview')!=null&&parseInt($('#totalCountReview').text())>0){$('#cntReviews').text($('#totalCountReview').text());}else{$('#cntReviews').text('0');}}
jqXHR.responseJSON;}else{console.log('ОШИБКИ ОТВЕТА сервера: '+respond.error);}},error:function(jqXHR,textStatus,errorThrown){console.log('ОШИБКИ AJAX запроса: '+textStatus);}});return false;}
$('.readmore-link').on('click',function(e){$(this).parent().parent().parent().find('.full-text').toggleClass('d-none');$(this).parent().parent().parent().find('.short-text').toggleClass('d-none');});$("#more-text").on("hide.bs.collapse",function(){$(".readmore-link.sr").text('Показать все');});$("#more-text").on("show.bs.collapse",function(){$(".readmore-link.sr").text('Скрыть');});$(function(){"use strict";$(".tabnav ul li").on("click",function(){var myID=$(this).attr("id");$(this).addClass("inactive").siblings().removeClass("inactive");$(".tab_inner").hide();console.log($(this).siblings());$("#"+myID+"-content").fadeIn(1000);});});